config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  
  devise_for :users, controllers: { registrations: 'users/registrations' }

  resources :jobs do
    member do
      get :apply, :approve, :unapprove
    end
  end

  resources :candidates, only: [:index, :create] do
    member do
      get :invite
    end
    collection do
      post :send_invitation
    end
  end

  resources :invitations, only: [] do
    member do
      get :accept, :reject
    end
    collection do
      patch :reject_job
    end
  end
end

app/models/job.rb
class Job < ApplicationRecord

	belongs_to :user
	belongs_to :organization
	has_many :candidates_jobs
	has_many :candidates, through: :candidates_jobs
	has_many :invitations
	
	validates :title, presence: true

	default_scope {where(:is_archive => false)}
	scope :approved, -> { where(is_approve: true) }
	
	def creator
		self.user.email	
	end
	def created
		self.created_at.strftime("%m/%d/%Y %H:%M %p")
	end

	def self.to_csv(options = {})
	  CSV.generate(options) do |csv|
	    csv << column_names
	    all.each do |product|
	      csv << product.attributes.values_at(*column_names)
	    end
	  end
	end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy, :apply,:approve,:unapprove]
  skip_before_action :authenticate_user!, only: :apply
  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = current_user.organization.jobs.approved
    respond_to do |format|
      format.html
      format.xls
    end
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
    if @job.is_archive
      flash[:alert] = "Job has been removed."
      redirect_to root_path
    end
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(job_params)
    @job.user_id = current_user.id
    @job.organization_id = current_user.organization_id

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.update_attribute :is_archive, true
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: 'Job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  def apply
    @candidate = Candidate.new
    if @job.blank?
      respond_to do |format|
        format.html { redirect_to root_path, alert: "No jobs found with id: #{params[:id]}." }
        format.json { head :no_content }
      end
    end      
  end

  def approve
    @job.update_attribute :is_approve, true   
    flash[:notice] = "Job has been approved."
    redirect_to request.referrer 
  end
  def unapprove
    @job.update_attribute :is_approve, false
    flash[:notice] = "Job has been unapproved."
    redirect_to request.referrer 
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find_by_id(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:title, :description)
    end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.erb
<div class="login-form">
  <%= form_with(model: job, local: true) do |f| %>
    <h2 class="text-center"><%=job.new_record? ? "Post Job" : "Update Job"%></h2>   
    <% if job.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(job.errors.count, "error") %> prohibited this job from being saved:</h2>

        <ul>
          <% job.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <%end%>
    <div class="form-group">
      <div class="input-group">
        <span class="input-group-addon"><i class="fa fa-user"></i></span>
        <%= f.text_field :title, autofocus: true, autocomplete: "email", class: "form-control", required: true, placeholder:"Title" %>    
      </div>
    </div>
    <div class="form-group">
      <div class="input-group">
        <span class="input-group-addon"><i class="fa fa-user"></i></span>
        <%= f.text_area :description, autofocus: true, autocomplete: "email", class: "form-control", required: true, placeholder:"Description" %>    
      </div>
    </div>
          
    <div class="form-group">
      <%= f.submit "Post Job", :class => "btn btn-primary login-btn btn-block" %>
    </div>
    <div class="clearfix"></div>
  <% end %>

</div>

app/views/jobs/apply.html.erb
<div class="apply_job_page">
	<div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
		<div class="job_details">
			<div class="job_th">Title:</div>
			<div class="job_td"><%= @job.title %></div>
			
			<div class="job_th">Description:</div>
			<div class="job_td"><%= @job.description %></div>

			<div class="job_th">Company:</div>
			<div class="job_td"><%= @job.organization.name %></div>
			
			<div class="job_th">Posted On:</div>
			<div class="job_td"><%= @job.created %></div>
		</div>
	</div>

	<div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
		<div class="login-form">
		  <%= form_for(@candidate) do |f| %>
		    <h2 class="text-center">Apply Job</h2>   
		    <div class="form-group">
		      <div class="input-group">
		          <span class="input-group-addon"><i class="fa fa-user"></i></span>
		          <%= f.text_field :name, autofocus: true, autocomplete: "email", class: "form-control", required: true, placeholder:"Name" %> 
		          <input type="hidden" name="job_id" value="<%=@job.id%>">   
		        </div>
		    </div>
		    <div class="form-group">
		      <div class="input-group">
		          <span class="input-group-addon"><i class="fa fa-user"></i></span>
		          <%= f.email_field :email, autofocus: true, autocomplete: "email", class: "form-control", required: true, placeholder:"Email" %>    
		        </div>
		    </div>
		        
		    <div class="form-group">
		      <%= f.submit "Apply Now", :class => "btn btn-primary login-btn btn-block" %>
		    </div>
		    <div class="clearfix"></div>
		  <% end %>
		</div>	
	</div>
	<div class="cb"></div>	
</div>

app/views/jobs/edit.html.erb
<%= render 'form', job: @job %>

<%= link_to 'Show', @job %> |
<%= link_to 'Back', jobs_path %>

app/views/jobs/index.html.erb
<h2>
  Download:
  <%= link_to "Excel", jobs_path(format: "xls") %>
</h2>
<%=render partial:"home/org_user"%>

app/views/jobs/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">ID</Data></Cell>
        <Cell><Data ss:Type="String">Title</Data></Cell>
        <Cell><Data ss:Type="String">Description</Data></Cell>
        <Cell><Data ss:Type="String">Applied Count</Data></Cell>
        <Cell><Data ss:Type="String">Posted On</Data></Cell>
        <Cell><Data ss:Type="String">Approved/Unapproved</Data></Cell>
      </Row>
    <% @jobs.each do |job| %>
      <Row>
        <Cell><Data ss:Type="Number"><%= job.id %></Data></Cell>
        <Cell><Data ss:Type="String"><%= job.title %></Data></Cell>
        <Cell><Data ss:Type="String"><%= job.description %></Data></Cell>
        <Cell><Data ss:Type="Number"><%= job.candidates.count %></Data></Cell>
        <Cell><Data ss:Type="String"><%= job.created %></Data></Cell>
        <Cell><Data ss:Type="String"><%= job.is_approve ? "Approved" : "Unapproved" %></Data></Cell>
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/jobs/new.html.erb
<%= render 'form', job: @job %>

<%= link_to 'Back', jobs_path %>

app/views/jobs/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @job.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @job.description %>
</p>

<%= link_to 'Edit', edit_job_path(@job) %> |
<%= link_to 'Back', jobs_path %>