config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  
  devise_for :users, controllers: { registrations: 'users/registrations' }

  resources :jobs do
    member do
      get :apply, :approve, :unapprove
    end
  end

  resources :candidates, only: [:index, :create] do
    member do
      get :invite
    end
    collection do
      post :send_invitation
    end
  end

  resources :invitations, only: [] do
    member do
      get :accept, :reject
    end
    collection do
      patch :reject_job
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!
  def index
    if user_signed_in? 
      if current_user.role == "org_user"
        @jobs = current_user.organization.jobs.order("created_at DESC")
      else
        @jobs = Job.all.order("created_at DESC")
      end
    else
      @jobs = Job.all.order("created_at DESC").approved
    end
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_admin.html.erb
<h1>Jobs</h1>

<table id="job_list" class="table table-hover table-striped">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Company</th>
      <th>Posted On</th>
      <th ></th>
    </tr>
  </thead>

  <tbody>
    <%if @jobs.present?%>
      <% @jobs.each do |job| %>
        <tr>
          <td><%= job.title %></td>
          <td><%= job.description %></td>
          <td><%= job.organization.name %></td>
          <td><%= job.created %></td>
          <td>
            <%if job.is_approve%>
              <%= link_to 'Unapprove', unapprove_job_path("#{job.id}") %>
            <%else%>
              <%= link_to 'Approve', approve_job_path("#{job.id}") %>
            <%end%>
              
          </td>
        </tr>
      <% end %>
    <%end%>
  </tbody>
</table>

<br>
<script type="text/javascript">
  $(document).ready(function() {
    $('#job_list').DataTable();
  } );
</script>

app/views/home/_candidate.html.erb
<h1>Jobs</h1>

<table id="job_list" class="table table-hover table-striped">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Company</th>
      <th>Posted On</th>
      <th ></th>
    </tr>
  </thead>

  <tbody>
    <%if @jobs.present?%>
      <% @jobs.each do |job| %>
        <tr>
          <td><%= job.title %></td>
          <td><%= job.description %></td>
          <td><%= job.organization.name %></td>
          <td><%= job.created %></td>
          <td><%= link_to 'Apply', apply_job_path("#{job.id}") %></td>
        </tr>
      <% end %>
    <%end%>
  </tbody>
</table>

<br>
<script type="text/javascript">
  $(document).ready(function() {
    $('#job_list').DataTable();
  } );
</script>

app/views/home/_org_user.html.erb
<h1>Jobs</h1>
<%= link_to 'New Job', new_job_path, :class => "btn btn-success" %>
<br><br>
<table id="job_list" class="table table-hover table-striped">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Company</th>
      <th>Applied Count</th>
      <th>Posted On</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <%if @jobs.present?%>
      <% @jobs.each do |job| %>
        <tr>
          <td><%= job.title %></td>
          <td><%= job.description %></td>
          <td><%= job.organization.name %></td>
          <td><%= job.candidates.count %></td>
          <td><%= job.created %></td>
          <td><%= job.is_approve ? "Approved" : "Unapproved" %></td>
          <td><%= link_to 'Show', job %></td>
          <td><%= link_to 'Edit', edit_job_path(job) %></td>
          <td><%= link_to 'Destroy', job, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    <%end%>
  </tbody>
</table>
<br>
<script type="text/javascript">
  $(document).ready(function() {
    $('#job_list').DataTable();
  } );
</script>

app/views/home/index.html.erb
<%unless user_signed_in?%>
  <%=render partial:"candidate"%>
<%else%>
  <%if current_user.role == "org_user"%>
    <%=render partial:"org_user"%>
  <%else%>
    <%=render partial:"admin"%>
  <%end%>
<%end%>

app/views/home/reject_invitation.html.erb
<div class="login-form">
  <%= form_with(model: @invitation, url:"/invitation/reject_job", local: true) do |f| %>
    <h2 class="text-center">Reject invitation</h2>   
    <% if @invitation.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@invitation.errors.count, "error") %> prohibited this @invitation from being saved:</h2>

        <ul>
          <% @invitation.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <%end%>
    <input type="hidden" name="id" value="<%=params[:id]%>">
    <div class="form-group">
      <div class="input-group">
        <span class="input-group-addon"><i class="fa fa-user"></i></span>
        <%= f.text_area :rejected_reason, autofocus: true, autocomplete: "email", class: "form-control", required: true, placeholder:"Reason for rejecting" %>    
      </div>
    </div>

    <div class="form-group">
      <%= f.submit "Reject", :class => "btn btn-primary login-btn btn-block" %>
    </div>
    <div class="clearfix"></div>
  <% end %>

</div>