config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  
  devise_for :users, controllers: { registrations: 'users/registrations' }

  resources :jobs do
    member do
      get :apply, :approve, :unapprove
    end
  end

  resources :candidates, only: [:index, :create] do
    member do
      get :invite
    end
    collection do
      post :send_invitation
    end
  end

  resources :invitations, only: [] do
    member do
      get :accept, :reject
    end
    collection do
      patch :reject_job
    end
  end
end

app/models/candidate.rb
class Candidate < ApplicationRecord
	has_many :candidates_jobs
	has_many :jobs, through: :candidates_jobs
	has_many :invitations

	validates :name, presence: true
	validates :email, presence: true
end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController
  skip_before_action :authenticate_user!
  def index
    @jobs = current_user.organization.jobs.includes({:candidates => :invitations})
  end

  def create
    job = Job.find_by_id(params[:job_id])
    if job.present? 
      @candidate = Candidate.find_by_email(params[:candidate][:email])
      p @candidate

      # checking candidate is new or not.
      if @candidate.present?
        # checking candidate already applied to the job or not.
        if @candidate.jobs.where(:id => job.id).first.present?
          respond_to do |format|
            format.html { redirect_to root_path, alert: "You have already applied to this job." }
            format.json { head :no_content }
          end
          return
        end
      else
        @candidate = Candidate.create(candidate_params)
      end
      CandidatesJob.create(:candidate_id => @candidate.id, :job_id => job.id)
      respond_to do |format|
        format.html { redirect_to request.referrer, notice: "You have successfully applied to this job." }
        format.json { head :no_content }
      end
    end
  end

  def invite
    @invitation = Invitation.new
  end

  def send_invitation
    candidate = Candidate.find_by_id(params[:candidate_id])
    job = Job.find_by_id(params[:job_id])
    if candidate.present?
      interview_date = DateTime.strptime(params[:invitation][:interview_date], '%d/%m/%Y - %H:%M') # params[:candidate][:interview_date]
      invitation = Invitation.create(:candidate_id => candidate.id, :organization_id => current_user.organization.id, :job_id => params[:job_id], :interview_date => interview_date)
      begin
        NotificationMailer.invite(candidate,job,invitation).deliver_now
        respond_to do |format|
          format.html { redirect_to root_path, notice: "Invitation sent for interview to: #{candidate.email}" }
        end
      rescue Exception => e
        respond_to do |format|
          format.html { redirect_to root_path, alert: e.message }
        end     
      end
    else
      respond_to do |format|
        format.html { redirect_to root_path, alert: "Candidate not found with id: #{params[:candidate_id]}" }
      end
    end
  end

  private
  def candidate_params
    params.require(:candidate).permit(:name, :email)
  end
end

app/helpers/candidate_helper.rb
module CandidateHelper
end

app/views/candidates/index.html.erb
<h1>Candidates</h1>
<br>
<table id="candidate_list" class="table table-hover table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Applied Job</th>
      <th>Applied On</th>
      <th>Status</th>
      <th>Response status</th>
      <th>Action</th>
    </tr>
  </thead>

  <tbody>
    <% @jobs.each do |job| %>
      <% job.candidates.each do |candidate| %>
        <tr>
          <%invitation = candidate.invitations.where(:job_id => job.id).last%>
          <td><%= candidate.name %></td>
          <td><%= candidate.email %></td>
          <td><%= job.title %></td>
          <td><%= candidate.jobs.where(:id => job.id).first.created_at %></td>
          <td><%=invitation.present? ? "Invitations sent" : "Invitations not sent"%></td>
          <td><%= invitation.present? ? (invitation.is_accepted ? "Accepted" : (invitation.is_accepted == false ? "Rejected" : "Not Decided")) : ""%></td>
          <td><a href="<%=invite_candidate_path(candidate.id, job_id: job.id)%>">Invite</a></td>
        </tr>
      <% end %>
   <%end%>
  </tbody>
  <tfoot>
    <tr>
      <th style="visibility:hidden;">Name</th>
      <th style="visibility:hidden;">Email</th>
      <th>Applied Job</th>
      <th style="visibility:hidden;">Applied On</th>
      <th>Status</th>
      <th>Response status</th>
      <th style="visibility:hidden;">Action</th>
    </tr>
  </tfoot>
</table>
<br>
<script type="text/javascript">
    $(document).ready(function() {
        $('#candidate_list').DataTable( {
            initComplete: function () {
                this.api().columns().every( function () {
                    var column = this;
                    var select = $('<select><option value=""></option></select>')
                        .appendTo( $(column.footer()).empty() )
                        .on( 'change', function () {
                            var val = $.fn.dataTable.util.escapeRegex(
                                $(this).val()
                            );
                            column
                                .search( val ? '^'+val+'$' : '', true, false )
                                .draw();
                        } );
     
                    column.data().unique().sort().each( function ( d, j ) {
                        select.append( '<option value="'+d+'">'+d+'</option>' )
                    } );
                } );
            }
        } );
    } );
</script>

app/views/candidates/invite.html.erb
<div class="login-form">
  <%= form_with(model: @invitation, url: send_invitation_candidates_path, local: true) do |f| %>
    <h2 class="text-center">Send invitation</h2>   
    <% if @invitation.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@invitation.errors.count, "error") %> prohibited this @invitation from being saved:</h2>

        <ul>
          <% @invitation.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <%end%>
    <input type="hidden" name="candidate_id" value="<%=params[:id]%>" >
    <input type="hidden" name="job_id" value="<%=params[:job_id]%>">
    <div class="form-group">
      <div class="input-append date form_datetime" data-date="2013-02-21T15:25:00Z">
        <%= f.text_field :interview_date, class: "form-control", :value => "", required: true, placeholder:"Interview Date"%> 
        <span class="add-on"><i class="icon-remove"></i></span>
        <span class="add-on"><i class="icon-calendar"></i></span>
      </div>
    </div>

    <div class="form-group">
      <%= f.submit "Post Job", :class => "btn btn-primary login-btn btn-block" %>
    </div>
    <div class="clearfix"></div>
  <% end %>

</div>

<script type="text/javascript">
    $(".form_datetime").datetimepicker({
        format: "dd/mm/yyyy - hh:ii",
        autoclose: true,
        todayBtn: true,
        startDate: new Date(),
        minuteStep: 10
    });
</script>  